Update core.py
Default for a missing PATH should be an empty string, not an empty list. Otherwise trying to call ".split" on it will throw "AttributeError: 'list' object has no attribute 'split'"